### ISSUE TITLE
Free Chlorine stopped working

### ISSUE THREAD

**Issue by kgalilio** [smurry/pool_controller#4]
Hi,
Thanks for the highly detailed guidance.
I have been using the pool_fc.py app in AppDaemon without any issues. Recently I have updated my hassio and AppDaemon to the latest releases, and for some reason I stopped getting the FC readings!
Not sure if it has anything to do with the upgrades, but those are about the only changes I've made recently.

The Error log in AppDaemon shows the following:
`2021-04-24 00:03:19.031463 WARNING free_chlorine: ------------------------------------------------------------
2021-04-24 00:03:19.031384 WARNING free_chlorine: Worker Ags: {'id': '808d559799674797b7b88deea12a8df5', 'name': 'free_chlorine', 'objectid': '572efedf5c354bd9a20f99ec18ac0fe3', 'type': 'state', 'function': >, 'attribute': 'state', 'entity': 'sensor.swimming_pool_ph', 'new_state': '11.77', 'old_state': '11.71', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}}
2021-04-24 00:03:19.031280 WARNING free_chlorine: Unexpected error in worker for App free_chlorine:
2021-04-24 00:03:19.031169 WARNING free_chlorine: ------------------------------------------------------------
2021-04-24 00:02:26.272568 WARNING free_chlorine: ------------------------------------------------------------
2021-04-24 00:02:26.272460 WARNING free_chlorine: Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 903, in worker
    funcref(
  File "/config/appdaemon/apps/pool_fc.py", line 33, in calc_fc
    for k,v in ch[last_orp].items():
KeyError: 0`

I have copied your pool_fc.py as is, therefore this is what I have at line 33:
`for k,v in ch[last_orp].items():`

I am wondering if anyone else is having the same problem, and if anyone has figured out how to fix it.
Any help would be greatly appreciated.

**Comment by smurry** [comment]
Thanks for sending the detailed troubleshooting data.  I haven’t seen this error before, however from the description I would say that it may be that your sensor.pool_orp is reading zero (0).  Can you check the state of this sensor and make sure it is reading something sensible?

 

--Stefan

 

From: kgalilio ***@***.***> 
Sent: Friday, April 23, 2021 4:26 PM
To: smurry/pool_controller ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [smurry/pool_controller] Free Chlorine stopped working (#4)

 

Hi,
Thanks for the highly detailed guidance.
I have been using the pool_fc.py app in AppDaemon without any issues. Recently I have updated my hassio and AppDaemon to the latest releases, and for some reason I stopped getting the FC readings!
Not sure if it has anything to do with the upgrades, but those are about the only changes I've made recently.

The Error log in AppDaemon shows the following:
2021-04-24 00:03:19.031463 WARNING free_chlorine: ------------------------------------------------------------ 2021-04-24 00:03:19.031384 WARNING free_chlorine: Worker Ags: {'id': '808d559799674797b7b88deea12a8df5', 'name': 'free_chlorine', 'objectid': '572efedf5c354bd9a20f99ec18ac0fe3', 'type': 'state', 'function': >, 'attribute': 'state', 'entity': 'sensor.swimming_pool_ph', 'new_state': '11.77', 'old_state': '11.71', 'pin_app': True, 'pin_thread': 0, 'kwargs': {'__thread_id': 'thread-0'}} 2021-04-24 00:03:19.031280 WARNING free_chlorine: Unexpected error in worker for App free_chlorine: 2021-04-24 00:03:19.031169 WARNING free_chlorine: ------------------------------------------------------------ 2021-04-24 00:02:26.272568 WARNING free_chlorine: ------------------------------------------------------------ 2021-04-24 00:02:26.272460 WARNING free_chlorine: Traceback (most recent call last): File "/usr/lib/python3.8/site-packages/appdaemon/threading.py", line 903, in worker funcref( File "/config/appdaemon/apps/pool_fc.py", line 33, in calc_fc for k,v in ch[last_orp].items(): KeyError: 0

I have copied your pool_fc.py as is, therefore this is what I have at line 33:
for k,v in ch[last_orp].items():

I am wondering if anyone else is having the same problem, and if anyone has figured out how to fix it.
Any help would be greatly appreciated.

**Comment by kgalilio** [comment]
For some reason my ORP sensor went crazy! I had to re-calibrate it again and all is fixed.
Thanks for your help.

**Comment by kgalilio** [comment]
Works like a charm.
